name: Lint and Jest Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - .gitignore
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - .gitignore
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"

      - run: npm ci

      - run: npm run lint

  tests:
    strategy:
      fail-fast: false
      matrix:
        suite: [unit, integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"

      - run: npm ci

      - run: npm run test:${{ matrix.suite }}
